### ISSUE TITLE
Enhancement - Support Enum Type

### ISSUE THREAD

**Issue by hieulw** [xnuinside/omymodels#10]
Currently, compiler cannot parse table with custom enum type
Eg.
```sql
CREATE TYPE "schema--notification"."ContentType" AS
 ENUM ('TEXT','MARKDOWN','HTML');
CREATE TABLE "schema--notification"."notification" (
    content_type "schema--notification"."ContentType"
);
```
Expected result
```python
from enum import Enum
from gino import Gino

db = Gino()


class ContentType(Enum):
    HTML = "HTML"
    MARKDOWN = "MARKDOWN"
    TEXT = "TEXT"

class Notification(db.Model):
    __tablename__ = 'notification'
    __table_args__ = dict(schema="schema--notification")

    content_type =db.Column(db.Enum(ContentType))
)
```

**Comment by xnuinside** [comment]
@hieulw , hello ) thanks for interest to the project, yes, I need to add construction " CREATE TYPE "schema--notification"."ContentType" AS
 ENUM " to https://github.com/xnuinside/simple-ddl-parser first. I will take it in work.

**Comment by xnuinside** [comment]
@hieulw, hi! I open WIP pr and released 0.5.0-a0 for tests https://github.com/xnuinside/omymodels/pull/13 it's contains Enums (see examples in test files) & uuid type. About Schema - one of the requirement for initial purposes of development this library was parse schema and put it to Gino() as argument. Because, when you have a 35 tables for example, and use schema for versioning, so you use 1 schema for all tables in same moments of time - it a lot of unnecessary code to put each schema separate in __table_args__. I think I will add config that allow set up such things, something like use_schema='per_table|globally'.

**Comment by xnuinside** [comment]
@hieulw  hello! I released 0.5.0 version with all changes, example in tests https://github.com/xnuinside/omymodels/blob/main/tests/test_models_simple.py#L117

**Comment by hieulw** [comment]
@xnuinside Great! It helps a lot. Now I'm trying to generate schema ddl from database (since `pg_dump` doesn't fit my need) and your project converts it to Gino model help my project development a lot faster.

**Comment by xnuinside** [comment]
@hieulw, can I close the issue?

**Comment by hieulw** [comment]
@xnuinside Yes, of course!
